config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  post 'user_token' => 'user_token#create'

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  resources :recipes
  resources :ingredients
  resources :mealplans

  namespace 'api' do
    namespace 'v1' do
      resources :users
      resources :recipes
      resources :ingredients
    end
  end
end

app/models/recipe.rb
# frozen_string_literal: true

##
# Base Recipe model
##
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :ingredient_recipes
  has_many :ingredients, through: :ingredient_recipes

  has_many :mealplan_recipes
  has_many :mealplans, through: :mealplan_recipes

  accepts_nested_attributes_for :ingredient_recipes

  validates :name, presence: true

  def estimated_price
    # TODO: Need to find a good way to use the quantity as a
    # multiplier
    ingredients.reduce(0) { |acc, ing| acc + ing.price }
  end

  scope :by_user_id, ->(id) { where(user_id: id) }
end

app/controllers/api/v1/recipes_controller.rb
# frozen_string_literal: true

module Api
  module V1
    ##
    # Basic api controller for Recipes CRUD actions
    ##
    class RecipesController < ApiController
      before_action :set_recipe, only: [:show, :update, :destroy]
      before_action :authenticate_user

      # GET /recipes
      # GET /recipes.json
      def index
        @recipes = Recipe.all.includes(:ingredients)
      end

      # GET /recipes/1
      # GET /recipes/1.json
      def show; end

      # POST /recipes
      # POST /recipes.json
      def create
        @recipe = Recipe.new(recipe_params)

        if @recipe.save
          render :show, status: :created, location: mapped_url(@recipe)
        else
          binding.pry
          render json: mapped_url(@recipe.errors),
                 status: :unprocessable_entity
        end
      end

      # PATCH/PUT /recipes/1
      # PATCH/PUT /recipes/1.json
      def update
        @recipe.ingredient_ids = params[:ingredients] if params[:ingredients]

        if @recipe.update(recipe_params)
          render :show, status: :ok, location: mapped_url(@recipe)
        else
          render json: mapped_url(@recipe.errors),
                 status: :unprocessable_entity
        end
      end

      # DELETE /recipes/1
      # DELETE /recipes/1.json
      def destroy
        @recipe.destroy
      end

      private

      def set_recipe
        @recipe = Recipe.includes(:ingredients).find(params[:id])
      end

      def recipe_params
        params.require(:recipe)
              .permit(:name, :description, :user_id, ingredients: [],)
      end

      def mapped_url(data)
        api_v1_recipe_url(data)
      end
    end
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

##
# Recipes class for server-rendered app
##
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_user
  before_action :set_recipe, only: [:edit, :show, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all.includes(:ingredients)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show; end

  def edit
    @available_ingredients = ::Services::Recipes::MapAvailableIngredients
                             .new(recipe: @recipe, user_id: current_user.id)
                             .call
    @ingredients = ::Services::Recipes::MapIngredientsEditData
                   .new(recipe: @recipe).call
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredient_recipes << IngredientRecipe.new
    @available_ingredients = Ingredient.by_user_id(current_user.id)
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    result = ::Services::Recipes::SetIngredientsService
             .new(recipe: @recipe, params: recipe_params).call

    if result
      redirect_to recipe_path(@recipe)
    else
      flash_errors(@recipe.errors)
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    success = ::Services::Recipes::SetIngredientsService
              .new(recipe: @recipe, params: recipe_params).call

    if success
      redirect_to recipes_path
    else
      flash_errors(@recipe.errors) unless @recipe.update(recipe_params)
      render :edit
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    if @recipe.destroy
      redirect_to recipes_path
    else
      render :show
    end
  end

  private

  def set_recipe
    @recipe = Recipe.includes(:ingredients, :ingredient_recipes)
                    .find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name,
                                   :description,
                                   ingredient_recipes_attributes: [
                                     :ingredient_id,
                                     :quantity
                                   ])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/edit.html.haml
= javascript_pack_tag 'forms/edit_recipe'
- initial_props = {                             |
  availableIngredients: @available_ingredients, |
  ingredients: @ingredients,                    |
  recipe: @recipe                               |
}.to_json                                       |

= csrf_meta_tags

%div{id: "edit-recipe-form", data: initial_props}

app/views/recipes/index.html.haml
.container.pt-2.flex.flex-col.items-center
  .flex.flex-row.items-center.justify-between.w-full.my-4.px-4
    %h3.text-black-light Recipe
    = link_to "New Recipe +", new_recipe_path, class: "btn btn-link btn-blue text-white"
  %table.w-full
    %thead
      %tr.text-center
        %th Name
        %th Description
    %tbody
      - @recipes.each do |recipe|
        %tr.text-center.py-4
          %td= link_to recipe.name, recipe_path(recipe)
          %td= recipe.description
          %td= button_to "Edit", edit_recipe_path(recipe), |
               class: "btn btn-blue", method: :get         |

app/views/recipes/new.html.haml
= javascript_pack_tag 'forms/create_recipe'
- initial_props = {                           |
  availableIngredients: @available_ingredients |
}.to_json                                     |

= csrf_meta_tags

%div{id: "create-recipe-form", data: initial_props}

app/views/recipes/show.html.haml
.container-md.flex.flex-col.card
  %h1
    = @recipe.name
  %h3.my-2.text-left
    = @recipe.description
  - @recipe.ingredient_recipes.each do |ingredient_recipe|
    - ingredient_recipe = IngredientRecipe.find(ingredient_recipe.id)
    %div
      %strong= "#{ingredient_recipe.ingredient_name}:"
      #{ingredient_recipe.quantity} #{ingredient_recipe.ingredient.unit}(s)
  %h3.my-2.text-left
    Estimated Price
    = number_to_currency(@recipe.estimated_price, precision: 2)

  %div.flex.flex-row.mt-6.items-center.my-2
    .visited:text-white.text-center.btn.btn-group-left.btn-blue.flex-1
      \#{button_to 'edit', edit_recipe_path(@recipe), method: :get, class: 'bg-blue text-white' }
    .visited:btn.btn-group-right.btn-red.flex-1
      \#{button_to "delete", @recipe, method: :delete, class: 'bg-red text-white' }