config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  post 'user_token' => 'user_token#create'

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  resources :recipes
  resources :ingredients
  resources :mealplans

  namespace 'api' do
    namespace 'v1' do
      resources :users
      resources :recipes
      resources :ingredients
    end
  end
end

app/models/ingredient.rb
# frozen_string_literal: true

##
# Base Ingredient model
##
class Ingredient < ApplicationRecord
  belongs_to :user
  has_many :ingredient_recipes
  has_many :recipes, through: :ingredient_recipes

  validates :name, presence: true
  validates :price, presence: true

  scope :by_user_id, ->(id) { where(user_id: id) }
end

app/controllers/api/v1/ingredients_controller.rb
# frozen_string_literal: true

module Api
  module V1
    ##
    # Basic api controller for Ingredients CRUD actions
    ##
    class IngredientsController < ApiController
      before_action :set_ingredient, only: [:show, :update, :destroy]
      before_action :authenticate_user

      # GET /ingredients
      # GET /ingredients.json
      def index
        @ingredients = Ingredient
                       .by_user_id(current_user.id)
                       .includes(:recipes)
      end

      # GET /ingredients/1
      # GET /ingredients/1.json
      def show; end

      # POST /ingredients
      # POST /ingredients.json
      def create
        @ingredient = Ingredient.new(ingredient_params)

        if @ingredient.save
          render :show, status: :created, location: mapped_url(@ingredient)
        else
          render json: mapped_url(@ingredient.errors),
                 status: :unprocessable_entity
        end
      end

      # PATCH/PUT /ingredients/1
      # PATCH/PUT /ingredients/1.json
      def update
        if @ingredient.update(ingredient_params)
          render :show, status: :ok, location: mapped_url(@ingredient)
        else
          render json: mapped_url(@ingredient.errors),
                 status: :unprocessable_entity
        end
      end

      # DELETE /ingredients/1
      # DELETE /ingredients/1.json
      def destroy
        @ingredient.destroy
      end

      private

      attr_reader :current_user

      def set_ingredient
        @ingredient = Ingredient.find(params[:id])
      end

      def ingredient_params
        params.require(:ingredient)
              .permit(:name, :description, :price, :recipes, :unit, :user_id)
      end

      def mapped_url(data)
        api_v1_ingredient_url(data)
      end
    end
  end
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

##
# Basic api controller for Ingredients CRUD actions
##
class IngredientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ingredient, only: [:edit, :show, :update, :destroy]
  before_action :require_user

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient
                   .by_user_id(current_user.id)
                   .includes(:recipes)
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show; end

  def edit; end

  def new
    @ingredient = Ingredient.new
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.user = current_user

    if @ingredient.save
      redirect_to ingredient_path(@ingredient)
    else
      flash_errors(@ingredient.errors)
      render 'new'
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    if @ingredient.update(ingredient_params)
      redirect_to ingredient_path(@ingredient)
    else
      flash_errors(@ingredient.errors)
      render 'update'
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    if @ingredient.destroy
      redirect_to ingredients_path
    else
      render 'show'
    end
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient)
          .permit(:name, :description, :price, :recipes, :unit)
  end
end

app/views/ingredients/edit.html.haml
.form-container
  %h2.py-2 Edit Ingredient
  = form_for(@ingredient, url: { action: "update" }) do |f|
    = f.label :name
    %br/
    = f.text_field :name, autofocus: true, placeholder: "Name", |
      required: true, class: "form-field"                       |
    = f.label :description
    = f.text_area :description, placeholder: "Description", |
      class: "form-field"                                   |
    = f.label :price
    %br/
    = f.number_field :price, placeholder: "Cost per unit", step: 0.01, |
      required: true, class: "form-field"                              |
    = f.label :unit
    %br/
    = f.text_field :unit, placeholder: "Unit of measurement", |
      required: true, class: "form-field"                     |
    .flex.justify-between.mt-4
      = submit_tag "Update", class: "btn-group-left btn-blue flex-1", |
        data: { disable_with: 'Updating...' }                         |
      = link_to 'Back', :back, class: 'btn-group-right btn-blue-rev text-center flex-1'

app/views/ingredients/index.html.haml
.container.pt-2.flex.flex-col.items-center
  .flex.flex-row.items-center.justify-between.w-full.my-4.px-4
    %h3.text-black-light Ingredients
    = link_to "New Ingredient +", new_ingredient_path, class: "btn btn-blue btn-link text-white"
  %table.w-full
    %thead
      %tr.text-center
        %th Name
        %th Description
        %th Price
        %th Unit
    %tbody
      - @ingredients.each do |ingredient|
        %tr.text-center
          %td= link_to ingredient.name, ingredient_path(ingredient)
          %td= ingredient.description
          %td= number_to_currency(ingredient.price, precision: 2)
          %td= ingredient.unit
          %td= button_to 'Edit', edit_ingredient_path(ingredient), |
              class: "btn btn-blue", method: :get                 |

app/views/ingredients/new.html.haml
.form-container
  %h2.py-2 New Ingredient
  = form_for(@ingredient, url: { action: "create" }) do |f|
    = f.label :name
    %br/
    = f.text_field :name, autofocus: true, placeholder: "Name", |
      required: true, class: "form-field"                       |
    = f.label :description
    = f.text_area :description, placeholder: "Description", |
      class: "form-field"                                   |
    = f.label :price
    %br/
    = f.number_field :price, placeholder: "Cost per unit", step: 0.01, |
      required: true, class: "form-field"                              |
    = f.label :unit
    %br/
    = f.text_field :unit, placeholder: "Unit of measurement", |
      required: true, class: "form-field"                     |
    .flex.justify-between.mt-4
      = submit_tag "Create", class: "btn-group-left btn-blue flex-1 rounded-r-none", |
        data: { disable_with: 'Creating...' }                                        |
      = link_to 'Back', ingredients_path, class: 'btn-group-right btn-blue-rev text-center flex-1 rounded-r-none'

app/views/ingredients/show.html.haml
.container-md.flex.flex-col.card
  %h1
    = @ingredient.name
    %h3.my-2
      = @ingredient.description
    %h3.my-2
      price: #{number_to_currency(@ingredient.price, precision: 2)} per #{@ingredient.unit}
      %div.flex.flex-row.mt-6.w-full.items-center
        .visited:text-white.text-center.btn.btn-group-left.btn-blue.flex-1
          \#{button_to 'edit', edit_ingredient_path(@ingredient), class: 'bg-blue text-white', method: :get}
        .visited:text-white.text-center.btn.btn-group-right.btn-red.flex-1
          \#{button_to "delete", @ingredient, method: :delete, class: 'bg-red text-white' }