config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  post 'user_token' => 'user_token#create'

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  resources :recipes
  resources :ingredients
  resources :mealplans

  namespace 'api' do
    namespace 'v1' do
      resources :users
      resources :recipes
      resources :ingredients
    end
  end
end

app/models/mealplan.rb
# frozen_string_literal: true

##
# Top-level class for mealplan, a collection of recipes
##
class Mealplan < ApplicationRecord
  belongs_to :user
  has_many :mealplan_recipes
  has_many :recipes, through: :mealplan_recipes

  scope :by_user_id, ->(id) { where(user_id: id) }
end

app/controllers/mealplans_controller.rb
class MealplansController < ApplicationController
  before_action :set_mealplan, only: [:show, :edit, :update, :destroy]

  # GET /mealplans
  # GET /mealplans.json
  def index
    @mealplans = Mealplan.all
  end

  # GET /mealplans/1
  # GET /mealplans/1.json
  def show
  end

  # GET /mealplans/new
  def new
    @mealplan = Mealplan.new
  end

  # GET /mealplans/1/edit
  def edit
  end

  # POST /mealplans
  # POST /mealplans.json
  def create
    @mealplan = Mealplan.new(mealplan_params)

    respond_to do |format|
      if @mealplan.save
        format.html { redirect_to @mealplan, notice: 'Mealplan was successfully created.' }
        format.json { render :show, status: :created, location: @mealplan }
      else
        format.html { render :new }
        format.json { render json: @mealplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mealplans/1
  # PATCH/PUT /mealplans/1.json
  def update
    respond_to do |format|
      if @mealplan.update(mealplan_params)
        format.html { redirect_to @mealplan, notice: 'Mealplan was successfully updated.' }
        format.json { render :show, status: :ok, location: @mealplan }
      else
        format.html { render :edit }
        format.json { render json: @mealplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mealplans/1
  # DELETE /mealplans/1.json
  def destroy
    @mealplan.destroy
    respond_to do |format|
      format.html { redirect_to mealplans_url, notice: 'Mealplan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_mealplan
    @mealplan = Mealplan.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def mealplan_params
    params.fetch(:mealplan, {})
  end
end

app/helpers/mealplans_helper.rb
module MealplansHelper
end

app/views/mealplans/_form.html.haml
= form_for @mealplan do |f|
  - if @mealplan.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mealplan.errors.count, "error")} prohibited this mealplan from being saved:"
      %ul
        - @mealplan.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/mealplans/edit.html.haml
%h1 Editing mealplan

= render 'form'

= link_to 'Show', @mealplan
\|
= link_to 'Back', mealplans_path

app/views/mealplans/index.html.haml
%h1 Mealplans

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @mealplans.each do |mealplan|
      %tr
        %td= link_to 'Show', mealplan
        %td= link_to 'Edit', edit_mealplan_path(mealplan), |
          class: 'btn btn-link btn-red text-white'
        %td= link_to 'Destroy', mealplan, method: :delete, |
          data: { confirm: 'Are you sure?' },              |
          class: 'btn btn-red text-white btn-link'

%br

= link_to 'New Mealplan', new_mealplan_path, class: 'btn btn-link btn-blue text-white'

app/views/mealplans/new.html.haml
%h1 New mealplan

= render 'form'

= link_to 'Back', mealplans_path

app/views/mealplans/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_mealplan_path(@mealplan)
\|
= link_to 'Back', mealplans_path