config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  post 'user_token' => 'user_token#create'

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  resources :recipes
  resources :ingredients
  resources :mealplans

  namespace 'api' do
    namespace 'v1' do
      resources :users
      resources :recipes
      resources :ingredients
    end
  end
end

app/views/layouts/_navbar.html.haml
.container-md.bg-teal.py-4.px-2
  .flex.items-center.justify-between.flex-wrap
    %h3
      = link_to "Mealplanner", root_url, class: "brand-name"
    .flex.items-center.justify-end
      - if user_signed_in?
        = link_to "Ingredients", ingredients_path, class: "home-link pr-4"
        = link_to "Recipes", recipes_path, class: "home-link px-4"
        = link_to "Mealplans", mealplans_path, class: "home-link px-4"
        = link_to "Sign Out", destroy_user_session_path,         |
          class: "home-link font-normal px-4" |
      - else
        = link_to "Sign In", new_user_session_path, class: "home-link px-4"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width,initial-scale=1.0", :name => "viewport"}/
    %title Mealplanner
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
  %body.text-base
    = csrf_meta_tag
    - if flash[:notice]
      .notice{"data-controller" => "notice"}= flash[:notice]
    - if flash[:alert]
      .alert{"data-controller" => "alert"}= flash[:alert]
    - if flash[:success]
      .success{"data-controller" => "notice"}= flash[:success]
    = render "layouts/navbar"
    .flex.flex-col.items-center
      = yield